services:
  douyin_tiktok_download_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: douyin_tiktok_download_api:local
    container_name: douyin_tiktok_download_api
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./crawlers/douyin/web/config.yaml:/app/crawlers/douyin/web/config.yaml
      - ./crawlers/tiktok/web/config.yaml:/app/crawlers/tiktok/web/config.yaml
      - ./crawlers/tiktok/app/config.yaml:/app/crawlers/tiktok/app/config.yaml
      - ./download:/app/download
